# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: test-snapshotclass
  namespace: test-csi
snapshotter: com.mapr.csi-kdf
parameters:
    restServers: CHANGETHIS
    cluster: CHANGETHIS
    csiSnapshotterSecretName: "mapr-provisioner-secrets" # Can be separate secret for snapshot only
    csiSnapshotterSecretNamespace: "test-csi"